version = 1

test_patterns = [
  "test_*.py"
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"

  [analyzers.meta]
  max_line_length = 88
  skip_doc_coverage = ["module", "magic", "init"]
  type_checker = 'mypy'
